### ISSUE TITLE
Visualizations not working

### ISSUE THREAD

**Issue by Maerchensarg** [kevkid/led_strip#2]
Hello. I set up an RPi3B with the current ISO today.

> Raspbian Stretch with desktop and recommended software
> Version: November 2018
> Release date: 2018-11-13
> Kernel version: 4.14

I followed both installation instructions and everything seems to work except for the visualizations. If I start them via web control, nothing happens. Console output:

```
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "led_strip/lights.py", line 52, in loop_visualization
    visualization.microphone.start_stream(visualization.microphone_update)
  File "/home/pi/audio-reactive-led-strip/python/microphone.py", line 21, in start_stream
    callback(y)
  File "/home/pi/audio-reactive-led-strip/python/visualization.py", line 230, in microphone_update
    mel_curve.setData(x=x, y=fft_plot_filter.update(mel))
NameError: global name 'mel_curve' is not defined
```

I can start the script "audio-reactive-led-strip/python/visualization.py" without any errors and I get the GUI and an output that reacts to the microphone.

I have no idea. Maybe someone of you?

Cheers and thanks.

**Comment by kevkid** [comment]
Hrmm something about jackserver try this:

```
pulseaudio --kill

jack_control start

jack_control exit

pulseaudio --start
```

found here: https://askubuntu.com/questions/557906/problem-starting-jack-server-jack-server-is-not-running-or-cannot-be-started

To be sure which python script are you starting up?

**Comment by Maerchensarg** [comment]
I tried pulseaudio --kill, but the command couldn't be found. So I executed "sudo apt-get install pulseaudio" and followed the next steps. Without success. It also made "visualization.py" not recognize the input correctly anymore. After I uninstalled it again, the "visualization.py" script runs with clean output again.

To test the mic:

`pi@WS2081:~ $ sudo python audio-reactive-led-strip/python/visualization.py`

And your script:

`pi@WS2081:~ $ sudo python led_strip/lights.py`

**Comment by Maerchensarg** [comment]
visualization.py gives me the same error but still works.

```
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: Datei oder Verzeichnis nicht gefunden
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: Datei oder Verzeichnis nicht gefunden
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: Datei oder Verzeichnis nicht gefunden
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: Datei oder Verzeichnis nicht gefunden
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = Datei oder Verzeichnis nicht gefunden
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
FPS 48 / 60
FPS 25 / 60
FPS 24 / 60
```

**Comment by kevkid** [comment]
Hrmm... and does this work?

`jack_control start`
oh, hrmm also try running it as sudo and see what happens.

**Comment by Maerchensarg** [comment]
```
pi@WS2081:~ $ jack_control start
--- start
```

After that, and a restart of lights.py, it still not works (with output: jack server is not running or cannot be started).

**Comment by kevkid** [comment]
and you ran sudo lights.py?

**Comment by Maerchensarg** [comment]
My lights.py is loaded via rc.local. What I did after a fresh reboot:

pi@WS2081:~ $ sudo pkill python
pi@WS2081:~ $ sudo jack_control start
--- start
pi@WS2081:~ $ sudo python led_strip/lights.py

I receive no errors until I start a visualization via webcontrol:

```
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "led_strip/lights.py", line 52, in loop_visualization
    visualization.microphone.start_stream(visualization.microphone_update)
  File "/home/pi/audio-reactive-led-strip/python/microphone.py", line 21, in start_stream
    callback(y)
  File "/home/pi/audio-reactive-led-strip/python/visualization.py", line 230, in microphone_update
    mel_curve.setData(x=x, y=fft_plot_filter.update(mel))
NameError: global name 'mel_curve' is not defined
```

**Comment by kevkid** [comment]
@Maerchensarg I'm not exactly sure why you are getting this error. I haven't had time to look too deeply into it, on my rpi 2 it works without issue, I am curious to see what you find out about it.

**Comment by Maerchensarg** [comment]
The feature would have been a nice feature for a project. This is no longer continued, so the setup is no longer available. Thanks anyway.
